# Generated by Django 5.0.4 on 2024-04-25 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comite',
            fields=[
                ('idComite', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.DateTimeField()),
                ('fechaActa', models.DateField()),
                ('detallesActa', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('idProceso', models.AutoField(primary_key=True, serialize=False)),
                ('fechaCitacion', models.DateField()),
                ('descargos', models.TextField()),
                ('decision', models.TextField()),
                ('estado', models.CharField(max_length=50)),
                ('justificacion', models.TextField()),
                ('motivo', models.TextField()),
                ('resumen', models.TextField()),
                ('evidencias', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='identificacion',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='PlanM',
            fields=[
                ('idPlanMejora', models.AutoField(primary_key=True, serialize=False)),
                ('situacion', models.TextField()),
                ('fechaInicio', models.DateField()),
                ('fechaLimite', models.DateField()),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Iniciar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficha', models.IntegerField()),
                ('cedulaUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.usuario')),
                ('idProceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.proceso')),
            ],
        ),
        migrations.CreateModel(
            name='Generar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPlanM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.planm')),
                ('idProceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.proceso')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idComite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.comite')),
                ('idProceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.proceso')),
            ],
        ),
    ]
